### PR TITLE
Certonly: Refactor manage_cron to ensure_cron with appropriate data type

### LINKED ISSUE #139: Disabling manage-cron does not remove crontab record
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.12
- Module version: 2.4.0

## How to reproduce (e.g Puppet code you use)
Set letsencrypt::certonly::manage-cron to true, sync, set to false, sync

## What are you seeing
crontab record and script are still present

## What behaviour did you expect instead
at least the crontab record should be removed

### PR DESCRIPTION
**Pull request by craigwatson**
#### Pull Request (PR) description
Ensures cron is removed when `manage_cron` is `false`.

#### This Pull Request (PR) fixes the following issues
Fixes #139

### CODE REVIEW

**Comment by craigwatson** [comment]
@ekohl fair point 👍

**Comment by ekohl** [comment]
That's a very fair point and I do agree `ensure_cron` is much better.

**Comment by craigwatson** [comment]
@Dan33l and @ekohl I agree, thanks for raising - I've updated the PR to use `$ensure_cron` with the correct data type. As this is a backwards-imcompatible change, how would you like to handle deprecation of `manage_cron`?

**Comment by Dan33l** [comment]
@craigwatson Thank you.

**Comment by baurmatt** [comment]
Ööööhm so as this is a breaking change, do we release 4.0.0?

**Pull request merged**
