### PR TITLE
#178 Add single quote around all domains names in shell commands

### LINKED ISSUE #178: Domain wildcard should be escaped or quoted in shell commands
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.9 + Hiera 4
- Ruby: 
- Distribution: Stretch
- Module version: 2.1.0

## How to reproduce (e.g Puppet code you use)

```
letsencrypt::certonly { 'somehost.subdomain.com':
  domains => ['somehost.subdomain.com', 'a.subdomain.com', 'b.subdomain.com'],
  plugin  => 'webroot',
}
letsencrypt::certonly { '*.subdomain.com':
  custom_plugins  => true,
}
```

## What are you seeing

When I want to create a certificate for a wildcard domain, using the wildcard character *, this one is interpreted by the shell and replaced by all files present in current working directory of the command
The shell globbing function work by replacing all * with all files that match. So if you have previously defined a certificate that match the pattern (see exemple below) the problem occur

This problem may not have already occur because when no file match, the shell leave the wildcard in place as in this example :

```
[root@laptop-pg03 test]$ ls    # an empty directory
[root@laptop-pg03 test]$ echo *
*
[root@laptop-pg03 test]$ touch fic
[root@laptop-pg03 test]$ echo *
fic
```

## What behaviour did you expect instead
The certbot command must be run with all domain name single quoted.

## Output log

```
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: usage:
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns:
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: it will attempt to use a webserver both for obtaining and installing the
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: certificate.
Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: certbot: error: unrecognized arguments: local.*.example.com preprod.*.example.com uat.*.example.com uat2.*.example.com
Error: 'certbot --text --agree-tos --non-interactive certonly -d *.*.example.com --manual --manual-auth-hook /usr/local/bin/certbot_rfc2136_auth.sh' returned 2 instead of one of [0]
Error: /Stage[main]/Profile::Letsencrypt/Brscommon::Define::Letsencrypt_certificate[*.*.example.com]/Letsencrypt::Certonly[letsencrypt-*.example.com]/Exec[letsencrypt certonly letsencrypt-*.example.com]/returns: change from notrun to 0 failed: 'certbot --text --agree-tos --non-interactive certonly -d *.*.example.com ' returned 2 instead of one of [0]
Certonly[letsencrypt-*.example.com]/File[/opt/puppetlabs/puppet/cache/letsencrypt/renew-letsencrypt-*.example.com.sh]/content:
--- /opt/puppetlabs/puppet/cache/letsencrypt/renew-letsencrypt-*.example.com.sh 2019-03-05 18:26:24.915103204 +0100
+++ /tmp/puppet-file20190305-11226-1ccf8ao    2019-03-05 18:31:11.273970967 +0100
@@ -1,2 +1,2 @@
 #!/bin/sh
-certbot --text --agree-tos --non-interactive certonly --keep-until-expiring -d *.example.com
\ No newline at end of file
+certbot --text --agree-tos --non-interactive certonly --keep-until-expiring -d *.*.example.com
\ No newline at end of file 
```

## Any additional information you'd like to impart

I will provided a PR to fix this issue

### PR DESCRIPTION
**Pull request by Turgon37**
#### Pull Request (PR) description
Add single quotes around dns domain name in shell command to prevent shell globbing

#### This Pull Request (PR) fixes the following issues
Fixes #178

### CODE REVIEW

**Comment by dhoppe** [comment]
@Turgon37 Please update the RSpec tests aswell.

**Comment by alexjfisher** [comment]
@Turgon37 Do you need some help with the spec tests?

**Comment by Turgon37** [comment]
Hello @alexjfisher , Thanks to you for your help proposal but I think I will get there. 
Just after this PR's creation I've seen that your module is well written with rspec. But as I cannot test on my local computer I searched to test at my work, and for now I've not found the time to do it.

So I will try here

**Comment by Rathios** [comment]
I ran into the same problem and tested out the fixes locally. Take a look at https://github.com/Rathios/puppet-letsencrypt/commit/4953fac7d1100e61ade6d020d6272c22624d8b6d, there's probably some more quote fixes to pick out.

**Comment by Turgon37** [comment]
Oh, I thinks it's ok :)

**Comment by Rathios** [comment]
Tested it here too and it works perfectly. 👍 @alexjfisher

**Comment by alexjfisher** [comment]
@Turgon37 Thanks!

**Comment by Turgon37** [comment]
Thanks to you, I use this module at work and it allow us to save money by using free certs for non production environment :)

**Pull request merged**
