### PR TITLE
Add dns-azure to allowed plugins

### PR DESCRIPTION
**Pull request by yachub**
#### Pull Request (PR) description

Add [dns-azure](https://github.com/terrycain/certbot-dns-azure) to list of allowed plugins. 

This is one of the 3rd party plugins listed at https://eff-certbot.readthedocs.io/en/stable/using.html#third-party-plugins

#### Caveat

I'm currently using this module on my branch on a RHEL 9 host, but the only caveat is the fastest way I found to get the plugin working was via the snap package:

```puppet
include snap

package { 'certbot':
  ensure          => installed,
  provider        => 'snap',
  install_options => ['classic'],
}

file { '/usr/bin/certbot':
  ensure  => link,
  source  => '/snap/bin/certbot',
  require => Package['certbot'],
}

package { 'certbot-dns-azure':
  ensure          => installed,
  provider        => 'snap',
  install_options => ['channel=edge'],
  require         => Package['certbot'],
}
```

And also had to run `snap set certbot trust-plugin-with-root=ok` before the last package resource, but didn't take the time yet to examine what changed on disk in order to create an exec resource to do that.

### CODE REVIEW

**Comment by bastelfreak** [comment]
thanks for the PR! Can you please document your steps in the README.md?

**Comment by yachub** [comment]
> thanks for the PR! Can you please document your steps in the README.md?

Absolutely!

**Comment by root-expert** [comment]
@yachub kinda off-topic

Are you by any chance using my [module](https://github.com/root-expert/puppet-snap/blob/master/REFERENCE.md) ?

It has a `snap_conf` resource to set `snap set certbot trust-plugin-with-root=ok` but seems I forgot to document it on the readme file :p.
You can check REFERENCE for more info.

**Comment by dduportal** [comment]
Hello there 👋 Dropping a message on behalf of the infrastructure team for the Jenkins project. We would be interested by this feature as we have puppet-managed (private) VMs on Azure that would benefit from this.

Thanks for the huge work!

**Review by ekohl — APPROVED** [review]

**Pull request merged**
