### PR TITLE
Drop EL7 support

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by silug** [comment]
@ekohl you'll also want to remove `data/os/CentOS/7.yaml`, correct?

I would also recommend removing CentOS 8 from `metadata.json` since it is EOL.

**Comment by ekohl** [comment]
> @ekohl you'll also want to remove `data/os/CentOS/7.yaml`, correct?

I swear I looked for that. Not sure why I didn't see it.

**Review by bastelfreak — APPROVED** [review]
looks good to me, but can we do a minor release before merging?

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-letsencrypt/pull/359

**Pull request merged**
