### PR TITLE
release 6.0.0

### PR DESCRIPTION
**Pull request by msalway**
#### Pull Request (PR) description
release 6.0.0

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by kenyon** [comment]
Fixes #232

**Comment by msalway** [comment]
Travis build failed due to the beaker-docker being incompatible with the docker-api 2.0.0 gem released today.

Have raised a PR upstream with puppetlabs to fix beaker-docker dependency:
https://github.com/puppetlabs/beaker-docker/pull/26

**Comment by alexjfisher** [comment]
beaker-docker 0.7.1 has been released.  Re-triggering the build.

**Comment by alexjfisher** [comment]
@msalway Thanks, and thanks for fixing beaker-docker too!

**Pull request merged**
