### PR TITLE
Raise upper bound version of stdlib & vcsrepo

### PR DESCRIPTION
**Pull request by mfaure**
#### Pull Request (PR) description

As new versions of `stdlib` and `vcsrepo` have been released, this PR updates `metadata.json` to their latest version

(Any feedback would be greatly appreciated :) )

#### This Pull Request (PR) fixes the following issues

(none)

### CODE REVIEW

**Comment by Dan33l** [comment]
@mfaure did you tested in your environment that module works well with the proposed versions of modules ? We have only some basics acceptance tests.

**Comment by mfaure** [comment]
@Dan33l Thanks for your feedback. Honestly I relied upon Travis. What else should be done ?

**Comment by ekohl** [comment]
@Dan33l why is this breaking? raising the upper bound is something I personally do even within a patch release.

**Comment by Dan33l** [comment]
> @Dan33l why is this breaking? raising the upper bound is something I personally do even within a patch release.

I added the tag because changing the major version. But i am wrong because we do not change the minimal required version. thank you for your reading. I remove the tag.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
