### PR TITLE
Add cron_before_command

### PR DESCRIPTION
**Pull request by gkopylov**
When you use 80 port for your web app and letsencrypt start updating it show the error that 80 port already bound to another app.  So we need to stop nginx for example(or another web service) to allow letsencrypt to update.

### CODE REVIEW

**Comment by gkopylov** [comment]
Hmm... I suppose we should remove tests for ruby 1.9.3(because of json_pure) and puppet 3.4.0(because of https://tickets.puppetlabs.com/browse/PUP-1597). @danzilio r?

**Comment by danzilio** [comment]
Hi @gkopylov, sorry about the delay on this. Could you rebase this PR and we can see where it's at?

**Comment by gkopylov** [comment]
@danzilio ok, done.

**Comment by juniorsysadmin** [comment]
@gkopylov More merge conflicts

**Comment by gkopylov** [comment]
@juniorsysadmin done.

**Pull request merged**
