### PR TITLE
release 2.6.0

### PR DESCRIPTION
**Pull request by Dan33l**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Can we please wait for the next modulesync before we do a release?

**Comment by bastelfreak** [comment]
Please rebase after https://github.com/voxpupuli/puppet-letsencrypt/pull/156 got merged

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-letsencrypt/pull/156 got merged. Please rebase and make this a 3.0.0 release.

**Comment by Dan33l** [comment]
So, with a major release update of the module, it looks interesting to update the version of certbot used by vcs method. The current version is about 2 years old.

**Comment by Dan33l** [comment]
since GitHub does not permit to change the source branch, i prefer to close this PRand open a new one with a correct name for source branch.

**Pull request closed without merging**
