### PR TITLE
Rename module to certbot

### PR DESCRIPTION
**Pull request by danzilio**

### CODE REVIEW

**Comment by TJM** [comment]
I got the following error, which might mean there are some dependency issues?

```
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Cron[certbot renew cron host.domain.com]/ensure: created
Error: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Error: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Wrapped exception:
No such file or directory - /etc/certbot/cli.ini
Error: /Stage[main]/Certbot::Config/Ini_setting[/etc/certbot/cli.ini  email]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Error: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Error: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Wrapped exception:
No such file or directory - /etc/certbot/cli.ini
Error: /Stage[main]/Certbot::Config/Ini_setting[/etc/certbot/cli.ini  server]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/certbot/cli.ini
Notice: /Stage[main]/Certbot::Config/File[/etc/certbot]/ensure: created
Notice: /Stage[main]/Certbot/Exec[initialize certbot]: Dependency Ini_setting[/etc/certbot/cli.ini  server] has failures: true
Notice: /Stage[main]/Certbot/Exec[initialize certbot]: Dependency Ini_setting[/etc/certbot/cli.ini  email] has failures: true
Warning: /Stage[main]/Certbot/Exec[initialize certbot]: Skipping because of failed dependencies
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]: Dependency Ini_setting[/etc/certbot/cli.ini  server] has failures: true
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]: Dependency Ini_setting[/etc/certbot/cli.ini  email] has failures: true
Warning: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]: Skipping because of failed dependencies
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Exec[start apache]: Dependency Ini_setting[/etc/certbot/cli.ini  server] has failures: true
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Exec[start apache]: Dependency Ini_setting[/etc/certbot/cli.ini  email] has failures: true
Warning: /Stage[main]/Lark::Profile::Letsencrypt/Exec[start apache]: Skipping because of failed dependencies
Notice: Finished catalog run in 9.45 seconds
```


Followed by:

```
Info: Applying configuration version '1471029666'
An unexpected error occurred:ofile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]/returns:
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]/returns: DialogError
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]/returns: Please see the logfiles in /var/log/letsencrypt for more details.
Error: certbot --agree-tos certonly -a standalone -d host.domain.com -d staging.domain.com --expand returned 1 instead of one of [0]
Error: /Stage[main]/Lark::Profile::Letsencrypt/Certbot::Certonly[host.domain.com]/Exec[certbot certonly host.domain.com]/returns: change from notrun to 0 failed: certbot --agree-tos certonly -a standalone -d host.domain.com -d staging.domain.com --expand returned 1 instead of one of [0]
Notice: /Stage[main]/Lark::Profile::Letsencrypt/Exec[start apache]: Dependency Exec[certbot certonly host.domain.com] has failures: true
Warning: /Stage[main]/Lark::Profile::Letsencrypt/Exec[start apache]: Skipping because of failed dependencies
Notice: Finished catalog run in 10.93 seconds
```

**Comment by juniorsysadmin** [comment]
@danzilio Re-naming a module is a bit more tricky than you think and possibly not worth the effort. Close?

**Comment by TJM** [comment]
@juniorsysadmin I have been using https://github.com/wearefine/puppet-letsencrypt/tree/certbot without too many issues. Back to the "normal" letsencrypt issues relating to getting random outside IPs access to port 443 on semi-private servers :)

**Comment by juniorsysadmin** [comment]
Closing due to inaction

**Pull request closed without merging**
