### PR TITLE
Add Fedora 31, drop Fedora 29

### PR DESCRIPTION
**Pull request by ekohl**
Fedora 29 is EOL since November 26th. Since there's no actual code change, it'll still continue to work for users. To make that happen, the Hiera hierachy is changed to allow setting variables per-OS.

### CODE REVIEW

**Comment by dhoppe** [comment]
Puppet does not provide any packages for Fedora 31.

**Comment by ekohl** [comment]
Should we drop the acceptance tests for it or not list it as supported at all?

**Comment by dhoppe** [comment]
Good question. Even if Puppet provides the required package, facterdb might be the next problem.

**Comment by ekohl** [comment]
On the other hand, nothing has really changed between F30 and F31 so how much value do the unit tests with facterdb actually provide?

**Comment by dhoppe** [comment]
I wonder how much sense it makes to test a rolling release. We do not do that with any other module.

**Comment by ekohl** [comment]
Fedora is not a rolling release. It has a [very clear 6 month release schedule](https://fedoraproject.org/wiki/Releases). this isn't for Fedora Rawhide and it's not like Arch.

**Comment by dhoppe** [comment]
Good to know, but the Facts and Puppet packages will still not be available on time in the future.

**Comment by Rathios** [comment]
Puppet packages for Fedora 31 have been available a while now. I'm one of those peeps using this module on Fedora 31, so would love to see this merged.

**Comment by ekohl** [comment]
Restarted the Fedora 31 builds

**Comment by ekohl** [comment]
@dhoppe any last comments?

**Pull request merged**
