### PR TITLE
modulesync 4.1.0 / Drop EoL Puppet 5 / Drop VCS install method

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 4.0.0

### CODE REVIEW

**Comment by ekohl** [comment]
Fedora 31 timed out on creating the Docker container, restarted the build.

**Review by ekohl — CHANGES_REQUESTED** [review]
Some odd is happening on Fedora 31 + Puppet 5. Failing in the same way now as before:
```
An error occurred while loading ./spec/acceptance/letsencrypt_plugin_dns_rfc2136_spec.rb.
```

**Comment by ekohl** [comment]
Given VCS mode has been broken for a while, should we drop it?

**Comment by bastelfreak** [comment]
yeah I think we should rip it out :(

**Comment by ekohl** [comment]
I took the liberty of leaving your commits out and remove VCS install method support. This must be mentioned in the changelog somewhere.

**Comment by ekohl** [comment]
It's green now. Sometimes the easiest thing is to just remove things :)

**Review by ekohl — APPROVED** [review]
I made a large number of changes so I'd appreciate if someone else also took a look.

**Pull request merged**
